### ISSUE TITLE
Uncaught ReferenceError: recursion is not defined

### ISSUE THREAD

**Issue by antobine** [ryuutatsuo88/dynomap#2]
Hello everyone,
I've been trying to implement this wonderful plugin [here] (http://prismadesign.com.ar/ceil/pais-x-pais.html)
The first time the page loads it works ok (altough some of the lower links seem to move from their original position), but after the page reloads I get an error saying **Uncaught ReferenceError: recursion is not defined**

I've looked for that line in the code and it's an if statement on line 234 of dynomap.js, the thing I can't figure out is where this variable **recursion** is coming from, as it doesn't appear again in the code.

I hope someone could help me out or point me in the direction of my problem. Thanks a lot!

**Comment by ryuutatsuo88** [comment]
Great catch!!! I fixed the issue. you can get the latest code and check.
